In [ ]:
print("Hello I'm Sina")

Hello I'm Sina


In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
print(torch.__version__)

2.11.0+cpu


In [ ]:
print(torch.__version__)

2.11.0+cpu


In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
rand_tensor = torch.rand(3, 4, 5)
rand_tensor

tensor([[[0.9751, 0.2209, 0.9806, 0.0794, 0.6731],
         [0.2575, 0.9167, 0.6799, 0.3252, 0.2441],
         [0.9665, 0.4083, 0.5849, 0.0742, 0.6559],
         [0.3008, 0.2420, 0.1590, 0.6085, 0.4598]],

        [[0.2147, 0.5589, 0.8497, 0.9874, 0.4335],
         [0.3350, 0.7101, 0.6023, 0.1242, 0.4377],
         [0.8012, 0.5495, 0.5399, 0.5754, 0.3566],
         [0.9141, 0.9229, 0.1479, 0.4478, 0.2775]],

        [[0.1457, 0.4877, 0.7171, 0.2296, 0.4628],
         [0.3270, 0.7163, 0.4506, 0.2985, 0.4745],
         [0.8922, 0.6490, 0.0846, 0.5460, 0.0202],
         [0.2039, 0.6813, 0.2790, 0.6660, 0.5997]]])

In [ ]:
rand_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.0201, 0.6107, 0.2374,  ..., 0.2579, 0.3304, 0.0133],
         [0.5029, 0.1589, 0.8894,  ..., 0.0636, 0.0450, 0.4001],
         [0.1078, 0.7237, 0.7645,  ..., 0.2580, 0.2351, 0.4972],
         ...,
         [0.3454, 0.6393, 0.4463,  ..., 0.5130, 0.6790, 0.6618],
         [0.9532, 0.9050, 0.3488,  ..., 0.8747, 0.6613, 0.1014],
         [0.8670, 0.9610, 0.3564,  ..., 0.9257, 0.4305, 0.7254]],

        [[0.1932, 0.3013, 0.5395,  ..., 0.3116, 0.2848, 0.3159],
         [0.9401, 0.4074, 0.6449,  ..., 0.1005, 0.6700, 0.3323],
         [0.6634, 0.6256, 0.2141,  ..., 0.5528, 0.0549, 0.9178],
         ...,
         [0.7110, 0.5369, 0.6426,  ..., 0.7300, 0.1168, 0.0337],
         [0.2501, 0.3528, 0.4799,  ..., 0.6639, 0.7948, 0.1611],
         [0.2758, 0.0316, 0.9577,  ..., 0.3338, 0.5856, 0.4874]],

        [[0.6266, 0.8323, 0.6804,  ..., 0.5556, 0.8794, 0.8258],
         [0.1512, 0.4525, 0.0879,  ..., 0.3650, 0.6536, 0.4569],
         [0.4569, 0.6314, 0.3763,  ..., 0.5113, 0.5441, 0.

Creating a range of tensors and tensors-like

In [ ]:
#Creating a range of tensors and tensors-like
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_thousend = torch.arange(start=1, end=1000, step=77)
one_to_thousend

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  #What datatype is the tensor (e.g. float32 or float16)
                               device=None,
                               requires_grad=False)
float_32_tensor
float_32_tensor.dtype


torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#Find out details about some tensor
some_tensor = torch.rand(3, 4)
some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4042, 0.8457, 0.1010, 0.7249],
        [0.0036, 0.3725, 0.4656, 0.8484],
        [0.1828, 0.5094, 0.6166, 0.6619]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#Manipulating Tensors (tensor operations)
#Tensor operations include:

*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication


In [ ]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 512 µs, sys: 42 µs, total: 554 µs
Wall time: 742 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 364 µs, sys: 26 µs, total: 390 µs
Wall time: 416 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(7, 5), torch.rand(5, 10))

tensor([[1.4226, 1.4822, 1.0500, 1.6157, 0.8312, 1.0559, 2.0444, 1.3498, 2.3054,
         1.9470],
        [1.2141, 1.7872, 0.5232, 1.8918, 1.2813, 1.5377, 1.8715, 0.9249, 1.7203,
         2.1537],
        [1.3206, 1.2411, 0.7319, 1.6235, 0.8943, 1.2360, 1.7541, 0.7921, 1.7719,
         1.8735],
        [1.4211, 1.8384, 0.8185, 1.6063, 0.8998, 1.6164, 1.6567, 1.3301, 1.7912,
         2.0131],
        [1.3795, 1.5117, 0.9303, 1.5590, 0.8161, 1.2533, 1.7630, 1.1708, 1.9797,
         1.9092],
        [1.8391, 1.4927, 0.6250, 2.0483, 1.0922, 2.1159, 1.9541, 0.8263, 1.6704,
         2.3534],
        [1.5320, 1.0798, 0.5353, 1.6299, 0.8291, 1.5622, 1.7655, 0.8252, 1.5036,
         1.8392]])

In [ ]:
torch.matmul(torch.rand(10, 5), torch.rand(5, 10)).shape

torch.Size([10, 10])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

print(tensor_A.shape)
print(tensor_B.shape)
torch.mm(tensor_A, tensor_B)

torch.Size([3, 2])
torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.mm(tensor_A, tensor_B.T)

In [ ]:
torch.mm(tensor_A.T, tensor_B)

##Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
tensor_x = torch.arange(0, 100, 10)
tensor_x

In [ ]:
torch.min(tensor_x)

In [ ]:
torch.max(tensor_x)

In [ ]:
torch.mean(tensor_x, dtype=torch.float32), tensor_x.type(torch.float32).mean()

In [ ]:
torch.sum(tensor_x), tensor_x.sum()

In [ ]:
%%time
value = 0
for i in range(len(tensor_x)):
  value+= tensor_x[i]
value/len(tensor_x)

In [ ]:
%%time
torch.mean(tensor_x.type(torch.float32))

In [ ]:
tensor_x.argmin()
tensor_x[0]

tensor(0)

In [ ]:
tensor_x.argmax()

tensor(9)

##Resahping, Viewing, Stacking, Squeezing, Unsqueezing

In [ ]:
#Create a tensor
import torch
tensor_C = torch.arange(1, 13)
tensor_C, tensor_C.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
tensor_C_reshaped = tensor_C.reshape(1, 9)
tensor_C_reshaped, tensor_C_reshaped.shape

RuntimeError: shape '[1, 9]' is invalid for input of size 10

In [ ]:
tensor_C_reshaped = tensor_C.reshape(3, 4)
tensor_C_reshaped, tensor_C_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
x_stacked = torch.stack([tensor_C, tensor_C, tensor_C, tensor_C], dim=0)
x_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
x_stacked = torch.stack([tensor_C, tensor_C, tensor_C, tensor_C], dim=1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

In [ ]:
tensor_C_Squeezed = tensor_C.squeeze(dim=0)
tensor_C, tensor_C_Squeezed, tensor_C_Squeezed.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 torch.Size([12]))

In [ ]:
tensor_C_Unsqueezed = tensor_C_Squeezed.unsqueeze(dim=0)
tensor_C_Squeezed, tensor_C_Unsqueezed, tensor_C_Unsqueezed.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [ ]:
tensor_C_Unsqueezed = tensor_C_Squeezed.unsqueeze(dim=1)
tensor_C_Squeezed, tensor_C_Unsqueezed, tensor_C_Unsqueezed.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]]),
 torch.Size([12, 1]))

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [2]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
x[0][1], x[0, 2]

(tensor([4, 5, 6]), tensor([7, 8, 9]))

In [5]:
x[0][1][1], x[0, 2, 2]

(tensor(5), tensor(9))

In [10]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [14]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [15]:
x[:, 1, 1]

tensor([5])

In [17]:
x[0, 0, :]

tensor([1, 2, 3])

In [21]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [23]:
x[0, 2, 2]

tensor(9)

In [24]:
import torch
import numpy as np

In [25]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [27]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [28]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))