In [2]:
print("Hello I'm Sina")

Hello I'm Sina


/bin/bash: line 1: nvidia-smi: command not found


In [11]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
print(torch.__version__)

2.11.0+cpu


In [7]:
print(torch.__version__)

2.11.0+cpu


In [3]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
vector.ndim

1

In [7]:
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix[0]

tensor([7, 8])

In [8]:
rand_tensor = torch.rand(3, 4, 5)
rand_tensor

tensor([[[0.1233, 0.7287, 0.7720, 0.1148, 0.0948],
         [0.0142, 0.8492, 0.9009, 0.2508, 0.4241],
         [0.8463, 0.3156, 0.7007, 0.2370, 0.1813],
         [0.4473, 0.0053, 0.3618, 0.9573, 0.4440]],

        [[0.2904, 0.0580, 0.7321, 0.1992, 0.9735],
         [0.7996, 0.3939, 0.8542, 0.7795, 0.2445],
         [0.3229, 0.1959, 0.4522, 0.0898, 0.7700],
         [0.1507, 0.9688, 0.2036, 0.3878, 0.1028]],

        [[0.3627, 0.7475, 0.5050, 0.2646, 0.9432],
         [0.2861, 0.3919, 0.1362, 0.8157, 0.6929],
         [0.9814, 0.4633, 0.9186, 0.8813, 0.5360],
         [0.9507, 0.9142, 0.5204, 0.1691, 0.0244]]])

In [9]:
rand_tensor.ndim

3

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.4730, 0.0443, 0.4699,  ..., 0.9290, 0.5194, 0.8653],
         [0.8766, 0.0250, 0.6049,  ..., 0.8231, 0.2454, 0.1312],
         [0.8232, 0.3685, 0.5272,  ..., 0.0579, 0.6308, 0.9814],
         ...,
         [0.3535, 0.3650, 0.6254,  ..., 0.4491, 0.8714, 0.6676],
         [0.8046, 0.2271, 0.2445,  ..., 0.2580, 0.7254, 0.5752],
         [0.0395, 0.7796, 0.3009,  ..., 0.2232, 0.6056, 0.2037]],

        [[0.0497, 0.1627, 0.5529,  ..., 0.2050, 0.0108, 0.1070],
         [0.3876, 0.1808, 0.8619,  ..., 0.9142, 0.0468, 0.2301],
         [0.8907, 0.8863, 0.6882,  ..., 0.4348, 0.9937, 0.8529],
         ...,
         [0.1071, 0.8726, 0.1428,  ..., 0.2894, 0.3610, 0.4704],
         [0.2388, 0.9634, 0.9673,  ..., 0.6964, 0.6434, 0.5289],
         [0.3219, 0.2346, 0.8049,  ..., 0.5520, 0.0256, 0.2079]],

        [[0.8435, 0.5576, 0.2008,  ..., 0.3511, 0.0853, 0.5750],
         [0.2061, 0.9428, 0.1062,  ..., 0.1021, 0.7668, 0.5915],
         [0.0581, 0.3339, 0.1328,  ..., 0.5035, 0.5606, 0.

#Creating a range of tensors and tensors-like

In [22]:
#Creating a range of tensors and tensors-like
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
one_to_thousend = torch.arange(start=1, end=1000, step=77)
one_to_thousend

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])